### ISSUE TITLE
Do something better than just returning `nil` when an exception is triggered

### ISSUE THREAD

**Issue by 3lvis** [Foreverland/NSDictionary-ANDYSafeValue#3]
When an exception is triggered `NSDictionary-ANDYSafeValue` just returns `nil`.

https://github.com/3lvis/NSDictionary-ANDYSafeValue/blob/master/Source/NSDictionary%2BANDYSafeValue.m#L14-L16

**Comment by 3lvis** [comment]
A suggestion by @kirill-c is to provide a way to log when this exception is triggered.

**Comment by kirill-c** [comment]
yeah, maybe just two separate methods (logging one and not logging one)

**Comment by 3lvis** [comment]
Closing old issues, since they might not be relevant.
